### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by buyonegetonefree** [cryptovandals/frontend#1]
- [x] Port [contracts](https://github.com/cryptovandals/contracts) to this repo @InitialShape 
- [x] Update `mint` function to any address @buyonegetonefree 
- [x] Create a sample ERC-721 token to sacrifice
- [x] Create basic front end:
  - [x] Select contract address
  - [x] Select `token_id`
  - [x] Vandalize image
  - [x] Trigger approve
  - [x] Upload image to IPFS
  - [x] Put the address of the image in `token_uri`, together with `name` and `description`
  - [x] Trigger `mint` in the `CryptoVandals` contract
